apiVersion: v1
kind: Service
metadata:
  name: argocd-server-external
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: argocd-server-75c77f9498-l9m2k.argocd-server.argocd.svc.cluster.local
