apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatterloop-web-deployment
  labels:
    app: chatterloop-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatterloop-web
  template:
    metadata:
      labels:
        app: chatterloop-web
    spec:
      containers:
      - name: chatterloop-web-cntnr
        image: johnpauloramil187/chatterloop_web:v2.1.3
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - name: http
          containerPort: 3004
      imagePullSecrets:
        - name: neon-systems-registry

---

apiVersion: v1
kind: Service
metadata:
  name: chatterloop-web-service
spec:
  selector:
    app: chatterloop-web
  ports:
    - name: http
      port: 110
      targetPort: 3004