apiVersion: apps/v1
kind: Deployment
metadata:
  name: neonremote-ui-deployment
  labels:
    app: neonremote-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neonremote-ui
  template:
    metadata:
      labels:
        app: neonremote-ui
    spec:
      containers:
        - name: neonremote-ui-cntnr
          image: johnpauloramil187/neonremote-ui:v0.0.1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 3006
      imagePullSecrets:
        - name: neon-systems-registry

---
apiVersion: v1
kind: Service
metadata:
  name: neonremote-ui-service
spec:
  selector:
    app: neonremote-ui
  ports:
    - name: http
      port: 111
      targetPort: 3006

