apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-ui
  namespace: rabbits
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 5672
      targetPort: 3006
