apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: neonsystems-letsencrypt-nginx
spec:
  acme:
    email: johnpauloramil.guimalan@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx-private-key
    solvers:
      - http01:
          ingress:
            class: nginx